package wire

import (
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// update regenerates the shared cross-language golden file. Run:
//
//	go test ./internal/wire -run TestWireFixtures -update
//
// The committed file (web/test/wire_fixtures.json) is consumed by BOTH this
// test and web/test/wire.test.js. Go is the source of truth for the byte
// layout; the JS test asserts its hand-mirrored decoder agrees with these
// exact bytes, so the two protocol implementations cannot silently drift.
var update = flag.Bool("update", false, "regenerate web/test/wire_fixtures.json")

// fixturesPath is relative to this package dir (internal/wire).
const fixturesPath = "../../web/test/wire_fixtures.json"

// fixtureFile is the on-disk schema. `decoded` mirrors the object shape the JS
// decoder/encoder uses; `hex` is the wire bytes.
type fixtureFile struct {
	Comment string      `json:"_comment"`
	Server  []frameCase `json:"server"` // server->client: Go encodes, JS decodes
	Client  []frameCase `json:"client"` // client->server: JS encodes, Go parses
}

type frameCase struct {
	Name    string          `json:"name"`
	Decoded json.RawMessage `json:"decoded"`
	Hex     string          `json:"hex"`
}

func canonicalServer() []frameCase {
	enc := func(b []byte) string { return hex.EncodeToString(b) }
	return []frameCase{
		{"welcome", json.RawMessage(`{"type":"welcome","id":7,"x":1000,"y":2000,"minX":0,"minY":0,"maxX":4095,"maxY":4095}`),
			enc(EncodeWelcome(7, 1000, 2000, 0, 0, 4095, 4095))},
		{"snapshot", json.RawMessage(`{"type":"snapshot","tick":42,"ents":[{"id":1,"x":100,"y":200},{"id":2,"x":-5,"y":4095}]}`),
			enc(EncodeSnapshot(42, []Ent{{1, 100, 200}, {2, -5, 4095}}))},
		{"enter", json.RawMessage(`{"type":"enter","id":9,"x":2048,"y":2048,"color":255,"name":"Zoë"}`),
			enc(EncodeEnter(9, 2048, 2048, 0x0000FF, "Zoë"))},
		{"leave", json.RawMessage(`{"type":"leave","id":9}`), enc(EncodeLeave(9))},
		{"pong", json.RawMessage(`{"type":"pong","t":123456}`), enc(EncodePong(123456))},
		{"paint", json.RawMessage(`{"type":"paint","x":2048,"y":2176,"color":3978315,"ownerId":3}`),
			enc(EncodePaint(2048, 2176, 0x3CB44B, 3))},
		{"shake", json.RawMessage(`{"type":"shake","id":5}`), enc(EncodeShake(5))},
	}
}

// canonicalClient builds frames the way the JS client encodes them, so the JS
// test can assert its encoder reproduces these exact bytes and the Go parser
// can assert it decodes them back to the expected fields.
func canonicalClient() []frameCase {
	hello := append([]byte{CHello, 3}, []byte("Bob")...)
	input := []byte{CInput, 0x2e, 0xfb, 0x09, 0x03} // x=-1234, y=777
	paint := []byte{CPaint}
	return []frameCase{
		{"hello", json.RawMessage(`{"type":1,"name":"Bob"}`), hex.EncodeToString(hello)},
		{"input", json.RawMessage(`{"type":2,"x":-1234,"y":777}`), hex.EncodeToString(input)},
		{"paint", json.RawMessage(`{"type":4}`), hex.EncodeToString(paint)},
	}
}

func TestWireFixtures(t *testing.T) {
	server := canonicalServer()
	client := canonicalClient()

	if *update {
		f := fixtureFile{
			Comment: "GENERATED by go test ./internal/wire -update. Shared golden vectors for the Go<->JS binary protocol. Do not hand-edit.",
			Server:  server,
			Client:  client,
		}
		b, err := json.MarshalIndent(f, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		b = append(b, '\n')
		if err := os.MkdirAll(filepath.Dir(fixturesPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fixturesPath, b, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", fixturesPath)
		return
	}

	// Golden check: the committed file must match freshly-encoded bytes, so a
	// change to any encoder without -update fails here (and would otherwise
	// silently break the JS client).
	raw, err := os.ReadFile(fixturesPath)
	if err != nil {
		t.Fatalf("read fixtures (run with -update to generate): %v", err)
	}
	var got fixtureFile
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatal(err)
	}

	assertHex(t, "server", got.Server, server)
	assertHex(t, "client", got.Client, client)

	// Round-trip the client frames through the real Go parser to confirm the
	// committed bytes decode to the documented fields.
	for _, c := range client {
		b, err := hex.DecodeString(c.Hex)
		if err != nil {
			t.Fatal(err)
		}
		msg, ok := ParseClient(b)
		if !ok {
			t.Fatalf("client %q: ParseClient returned ok=false", c.Name)
		}
		switch c.Name {
		case "hello":
			if msg.Type != CHello || msg.Name != "Bob" {
				t.Fatalf("hello parsed to %+v", msg)
			}
		case "input":
			if msg.Type != CInput || msg.X != -1234 || msg.Y != 777 {
				t.Fatalf("input parsed to %+v", msg)
			}
		case "paint":
			if msg.Type != CPaint {
				t.Fatalf("paint parsed to %+v", msg)
			}
		}
	}
}

func assertHex(t *testing.T, section string, committed, fresh []frameCase) {
	t.Helper()
	if len(committed) != len(fresh) {
		t.Fatalf("%s: committed has %d cases, code has %d (regenerate with -update)",
			section, len(committed), len(fresh))
	}
	byName := map[string]string{}
	for _, c := range committed {
		byName[c.Name] = c.Hex
	}
	for _, f := range fresh {
		if byName[f.Name] != f.Hex {
			t.Errorf("%s/%s: bytes drifted.\n committed: %s\n encoder:   %s\nregenerate with -update",
				section, f.Name, byName[f.Name], f.Hex)
		}
	}
}
